WebApplication1/Controllers/AuthorsController.cs
using e_shop.Data;
using e_shop.Data.Services;
using e_shop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace e_shop.Controllers
{
    public class AuthorsController : Controller
    {

            private readonly IAuthorsService _service;
            public AuthorsController(IAuthorsService service)
            {
                _service=service;
            }
            public async Task<IActionResult> Index(string searchString)
            {
                var allAuthors = await _service.GetAll();
                if (!String.IsNullOrEmpty(searchString))
                {

                    allAuthors = allAuthors.Where(n => n.FirstName.Contains(searchString, StringComparison.OrdinalIgnoreCase) || n.LastName.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
                }
                return View(allAuthors);
            }
        //Get: Books/Create
            public IActionResult Create()
            {
                return View();
            }
            [HttpPost]
            public async Task<IActionResult> Create(Author author)
            {
                if (!ModelState.IsValid)
                {
                    return View(author);
                }
                _service.Add(author);
                return RedirectToAction(nameof(Index));
            }

            //Get: Edit
            public async Task<IActionResult> Edit(int id)
            {
                var actorDetails = await _service.GetByIdAsync(id);
                if(actorDetails == null)
                {
                    return View("NotFound");
                }
                return View(actorDetails);
            }
            [HttpPost]
            public async Task<IActionResult> Edit(int id, Author author)
            {
                if (!ModelState.IsValid)
                {
                    return View(author);
                }
                await _service.UpdateAsync(author);
                return RedirectToAction(nameof(Index));
            }
            public async Task<IActionResult> Delete(int id)
            {
                var authorDetails = await _service.GetByIdAsync(id);
                if (authorDetails == null) return View("NotFound");
                return View(authorDetails);
            }
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                var authorDetails = await _service.GetByIdAsync(id);
                if (authorDetails == null) return View("NotFound");

                await _service.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
    }
}

WebApplication1/Controllers/BooksController.cs
using e_shop.Data;
using e_shop.Data.Services;
using e_shop.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data.Services;
using WebApplication1.viewModel;

namespace e_shop.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksService _service;
        private readonly IAuthorsService _authorsService;
        private readonly IGenresService _genresService;
        private readonly IBooksGenresService _bookGenresService;
        private readonly IPhotosService _photoService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUserBooksService _userBooksService;
        public BooksController(IBooksService service,IAuthorsService authorsService,IGenresService genresService,IBooksGenresService bookGenresService,IPhotosService photoService, IWebHostEnvironment webHostEnvironment, IUserBooksService userBooksService)
        {
            _service = service;
            _authorsService = authorsService;
            _genresService = genresService;
            _bookGenresService = bookGenresService;
            _photoService = photoService;
            _webHostEnvironment = webHostEnvironment;
            _userBooksService = userBooksService;
        }
        public async Task<IActionResult> Index(string searchString1, string searchString2, string searchString3)
        {
            var allBooks = await _service.GetAllAsync();
            if(!String.IsNullOrEmpty(searchString1))
            {
                
                allBooks = allBooks.Where(n => n.Title.Contains(searchString1, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            if (!String.IsNullOrEmpty(searchString2))
            {
                allBooks = allBooks.Where(n => n.Books_Genres.Any(
                        bg => bg.Genre.GenreName.Contains(searchString2, StringComparison.OrdinalIgnoreCase))
                );
            }
            if (!String.IsNullOrEmpty(searchString3))
            {
                allBooks = allBooks.Where(n => n.Author.FirstName.Contains(searchString3, StringComparison.OrdinalIgnoreCase) || n.Author.LastName.Contains(searchString3, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            return View(allBooks);
        }
        //Get: Books/Create
        public async Task<IActionResult> Create()
        {
            IEnumerable<Author> authors = await _authorsService.GetAll();
            IEnumerable<Genre> genres = await _genresService.GetAll();
            CreateBooksViewModel newVM = new CreateBooksViewModel()
            {
                Author = authors,
                Genres = genres,
            };
            return View(newVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateBooksViewModel bookVM)
        {
            if(!ModelState.IsValid)
            {
                IEnumerable<Author> author = await _service.GetAllAuthors();
                IEnumerable<Genre> genres = await _service.GetAllGenres();
                bookVM.Author = author;
                bookVM.Genres = genres;
                ModelState.AddModelError("", "Failed to add book");
                return View(bookVM);
            }
            var result = await _photoService.AddPhotoAsync(bookVM.FrontPage);
            if(bookVM.DownloadPdf!=null)
            {
                string folder = "BooksPdf/";
                bookVM.DownloadUrl=await UploadFile(folder,bookVM.DownloadPdf);
            }
            var newBook = new Book()
            {
                Title = bookVM.Title,
                YearPublished = bookVM.YearPublished,
                NumPages = bookVM.NumPages,
                Description = bookVM.Description,
                Publisher = bookVM.Publisher,
                FrontPage = result.Url.ToString(),
                AuthorId = bookVM.AuthorId,
                DownloadUrl = bookVM.DownloadUrl,
            };
            _service.Add(newBook);

            Book newLastBook = await _service.GetLastBook();
            foreach (var genreId in bookVM.GenreIds)
            {
                BookGenre bookGenre = new BookGenre()
                {
                    BookId = newLastBook.Id,
                    GenreId = genreId,
                };
                _bookGenresService.Add(bookGenre);
            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> SearchByAuthorId(int id)
        {
            IEnumerable<Book> books = await _service.GetBooksByAuthorId(id);
            return View(books);
        }
        //Get: Book/Delete
        public async Task<IActionResult> Delete(int id)
        {
            Book book = await _service.GetByIdAsync(id);
            if(book==null)
            {
                return View("NotFound");
            }
            return View(book);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteBookConfirmed(int id)
        {
            Book book=await _service.GetByIdAsync(id);
            if(book==null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        //Get: Books/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var bookDetails = await _service.GetByIdAsync(id);
            bool hasBook = false;
            if (User.Identity.IsAuthenticated)
            {
                hasBook = _userBooksService.HasBook(id);
            }
            if (bookDetails == null)
            {
                return View("NotFound");
            }
            DetailsViewModel detailsVM = new DetailsViewModel()
            {
                Book = bookDetails,
                HasBook = hasBook,
            };
            return View(detailsVM);

        }

        public async Task<IActionResult> Edit(int id)
        {
            Book book = await _service.GetByIdAsyncNoTracking(id);
            if (book == null)
            {
                return View("NotFound");
            }
            IEnumerable<Author> authors = await _service.GetAllAuthors();
            IEnumerable<Genre> genres = await _service.GetAllGenres();
            List<int> genreIds = new List<int>();
            foreach (var genre in book.Books_Genres)
            {
                genreIds.Add(genre.GenreId);
            }
            EditBooksViewModel bookVM = new EditBooksViewModel()
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                YearPublished = book.YearPublished,
                NumPages = book.NumPages,
                Publisher = book.Publisher,
                FrontPageUrl = book.FrontPage,
                DownloadUrl = book.DownloadUrl,
                Authors = authors,
                Genres = genres,
                AuthorId = book.AuthorId,
                GenreIds = genreIds,
            };
            return View(bookVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditBooksViewModel bookVM)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<Author> authors = await _service.GetAllAuthors();
                bookVM.Authors = authors;
                IEnumerable<Genre> genres = await _service.GetAllGenres();
                bookVM.Genres = genres;
                ModelState.AddModelError("", "Failed to edit book");
                return View(bookVM);
            }
            var result = await _photoService.AddPhotoAsync(bookVM.FrontPage);
            if (bookVM.DownloadPdf != null)
            {
                string folder = "BooksPdf/";
                bookVM.DownloadUrl = await UploadFile(folder, bookVM.DownloadPdf);
            }
            if (bookVM != null)
            {
                Book newBook = new Book()
                {
                    Id = bookVM.Id,
                    Title = bookVM.Title,
                    Description = bookVM.Description,
                    YearPublished = bookVM.YearPublished,
                    NumPages = bookVM.NumPages,
                    Publisher = bookVM.Publisher,
                    FrontPage = result.Url.ToString(),
                    DownloadUrl = bookVM.DownloadUrl,
                    AuthorId = bookVM.AuthorId,
                };
                _service.Update(id,newBook);
                IEnumerable<BookGenre> bookGenres = await _bookGenresService.GetAll();
                foreach (var bg in bookGenres)
                {
                    if (bg.BookId == id)
                    {
                        _bookGenresService.Delete(bg);
                    }
                }
                foreach (var genreId in bookVM.GenreIds)
                {
                    BookGenre bookGenre = new BookGenre()
                    {
                        BookId = bookVM.Id,
                        GenreId = genreId,
                    };
                    _bookGenresService.Add(bookGenre);
                }

                return Redirect("/Books/Details/" + id);
            }
            else
            {
                IEnumerable<Author> authors = await _service.GetAllAuthors();
                bookVM.Authors = authors;
                IEnumerable<Genre> genres = await _service.GetAllGenres();
                bookVM.Genres = genres;
                return View(bookVM);
            }
        }
        private async Task<string> UploadFile(string folderPath, IFormFile file)
        {
            if (folderPath == null)
            {
                throw new ArgumentNullException(nameof(folderPath), "Folder path cannot be null.");
            }

            // Combine folder path and file name

WebApplication1/Controllers/GenresController.cs
using e_shop.Data;
using e_shop.Data.Services;
using e_shop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace e_shop.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenresService _service;
        public GenresController(IGenresService service)
        {
            _service=service;
        }
        public async Task<IActionResult> Index()
        {
            var allGenres = await _service.GetAll();
            return View(allGenres);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("GenreName")] Genre genre)
        {
            if (!ModelState.IsValid)
            {
                return View(genre);
            }
            _service.Add(genre);
            return RedirectToAction(nameof(Index));
        }

        //Actors/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var genreDetails=await _service.GetByIdAsync(id);
            if (genreDetails == null) return View("NotFound");
            return View(genreDetails);
        }
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genreDetails = await _service.GetByIdAsync(id);
            if (genreDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var genreDetails = await _service.GetByIdAsync(id);
            if (genreDetails == null)
            {
                return View("NotFound");
            }
            return View(genreDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Genre genre)
        {
            if (!ModelState.IsValid)
            {
                return View(genre);
            }
            await _service.UpdateAsync(genre);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplication1/Controllers/UserBooksController.cs
using e_shop.Data;
using e_shop.Models;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data.Services;

namespace WebApplication1.Controllers
{
    public class UserBooksController : Controller
    {
        public readonly IUserBooksService _userBooksService;
        public UserBooksController(IUserBooksService userBooksService)
        {
            _userBooksService=userBooksService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Book> myBooks = await _userBooksService.GetAllUserBooks();
            return View(myBooks);
        }
        public async Task<IActionResult> BuyBook(int id)
        { 
            var curUser = _userBooksService.GetCurrentUserId();
            bool isBook = _userBooksService.BookExists(id);
            if(isBook) { return Redirect("/Books/Index/"); }
            UserBook newUB = new UserBook()
            {
                AppUser =curUser,
                BookId = id,
            };
            _userBooksService.Add(newUB);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var userBook = _userBooksService.GetUserBook(id);
            _userBooksService.Delete(userBook);
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e_shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/e_shop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body style="background-color: beige;">
    <header style="background-color: darkslategrey; font-size: 17px; padding: 5px;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Index" style="font-size: 22px; text-decoration: underline; color: antiquewhite;">.BookStore</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse">
                        <ul class="navbar-nav">
                            <li class="navbar-nav">
                            <a style="color: antiquewhite;" class="nav-link" asp-controller="Books" asp-action="Index"><i class="bi bi-shop-window"></i> Books</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a style="color: antiquewhite;"class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="navbarDropdown" role="button" data-toggle="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Additional
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Authors" asp-action="Index"><i class="bi bi-feather"> Authors</i></a>
                                    <a class="dropdown-item" asp-controller="Genres" asp-action="Index"><i class="bi bi-emoji-laughing"> Genres</i></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                @if(User.Identity.IsAuthenticated)
                {
                <div style="display: flex; width: 30%;">
                    @if(User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link" style="color: antiquewhite; text-decoration: none; margin-right: 10px;" asp-action="Index" asp-controller="UserBooks"><i class="bi bi-book"></i> My Books </a>
                        <form asp-area="" asp-controller="Account" asp-action="Logout">
                            <button class="btn btn-danger" style="margin-right: 10px;">Log out</button>
                        </form>
                    }
                </div>
                }
                else
                {
                    <div style="display: flex; width: 22%;">
                    <a class="nav-link btn btn-outline-secondary" style="color: antiquewhite; text-decoration: none; margin-right: 10px;" asp-action="Register" asp-controller="Account">Register </a>
                        <a class="nav-link btn btn-success" style="color: antiquewhite; text-decoration: none; margin-right: 10px;" asp-action="Login" asp-controller="Account">Login </a>
                    </div>
                }
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>