WebApplication1/Controllers/BooksController.cs
using e_shop.Data;
using e_shop.Data.Services;
using e_shop.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data.Services;
using WebApplication1.viewModel;

namespace e_shop.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksService _service;
        private readonly IAuthorsService _authorsService;
        private readonly IGenresService _genresService;
        private readonly IBooksGenresService _bookGenresService;
        private readonly IPhotosService _photoService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUserBooksService _userBooksService;
        public BooksController(IBooksService service,IAuthorsService authorsService,IGenresService genresService,IBooksGenresService bookGenresService,IPhotosService photoService, IWebHostEnvironment webHostEnvironment, IUserBooksService userBooksService)
        {
            _service = service;
            _authorsService = authorsService;
            _genresService = genresService;
            _bookGenresService = bookGenresService;
            _photoService = photoService;
            _webHostEnvironment = webHostEnvironment;
            _userBooksService = userBooksService;
        }
        public async Task<IActionResult> Index(string searchString1, string searchString2, string searchString3)
        {
            var allBooks = await _service.GetAllAsync();
            if(!String.IsNullOrEmpty(searchString1))
            {
                
                allBooks = allBooks.Where(n => n.Title.Contains(searchString1, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            if (!String.IsNullOrEmpty(searchString2))
            {
                allBooks = allBooks.Where(n => n.Books_Genres.Any(
                        bg => bg.Genre.GenreName.Contains(searchString2, StringComparison.OrdinalIgnoreCase))
                );
            }
            if (!String.IsNullOrEmpty(searchString3))
            {
                allBooks = allBooks.Where(n => n.Author.FirstName.Contains(searchString3, StringComparison.OrdinalIgnoreCase) || n.Author.LastName.Contains(searchString3, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            return View(allBooks);
        }
        //Get: Books/Create
        public async Task<IActionResult> Create()
        {
            IEnumerable<Author> authors = await _authorsService.GetAll();
            IEnumerable<Genre> genres = await _genresService.GetAll();
            CreateBooksViewModel newVM = new CreateBooksViewModel()
            {
                Author = authors,
                Genres = genres,
            };
            return View(newVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateBooksViewModel bookVM)
        {
            if(!ModelState.IsValid)
            {
                IEnumerable<Author> author = await _service.GetAllAuthors();
                IEnumerable<Genre> genres = await _service.GetAllGenres();
                bookVM.Author = author;
                bookVM.Genres = genres;
                ModelState.AddModelError("", "Failed to add book");
                return View(bookVM);
            }
            var result = await _photoService.AddPhotoAsync(bookVM.FrontPage);
            if(bookVM.DownloadPdf!=null)
            {
                string folder = "BooksPdf/";
                bookVM.DownloadUrl=await UploadFile(folder,bookVM.DownloadPdf);
            }
            var newBook = new Book()
            {
                Title = bookVM.Title,
                YearPublished = bookVM.YearPublished,
                NumPages = bookVM.NumPages,
                Description = bookVM.Description,
                Publisher = bookVM.Publisher,
                FrontPage = result.Url.ToString(),
                AuthorId = bookVM.AuthorId,
                DownloadUrl = bookVM.DownloadUrl,
            };
            _service.Add(newBook);

            Book newLastBook = await _service.GetLastBook();
            foreach (var genreId in bookVM.GenreIds)
            {
                BookGenre bookGenre = new BookGenre()
                {
                    BookId = newLastBook.Id,
                    GenreId = genreId,
                };
                _bookGenresService.Add(bookGenre);
            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> SearchByAuthorId(int id)
        {
            IEnumerable<Book> books = await _service.GetBooksByAuthorId(id);
            return View(books);
        }
        //Get: Book/Delete
        public async Task<IActionResult> Delete(int id)
        {
            Book book = await _service.GetByIdAsync(id);
            if(book==null)
            {
                return View("NotFound");
            }
            return View(book);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteBookConfirmed(int id)
        {
            Book book=await _service.GetByIdAsync(id);
            if(book==null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        //Get: Books/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var bookDetails = await _service.GetByIdAsync(id);
            bool hasBook = false;
            if (User.Identity.IsAuthenticated)
            {
                hasBook = _userBooksService.HasBook(id);
            }
            if (bookDetails == null)
            {
                return View("NotFound");
            }
            DetailsViewModel detailsVM = new DetailsViewModel()
            {
                Book = bookDetails,
                HasBook = hasBook,
            };
            return View(detailsVM);

        }

        public async Task<IActionResult> Edit(int id)
        {
            Book book = await _service.GetByIdAsyncNoTracking(id);
            if (book == null)
            {
                return View("NotFound");
            }
            IEnumerable<Author> authors = await _service.GetAllAuthors();
            IEnumerable<Genre> genres = await _service.GetAllGenres();
            List<int> genreIds = new List<int>();
            foreach (var genre in book.Books_Genres)
            {
                genreIds.Add(genre.GenreId);
            }
            EditBooksViewModel bookVM = new EditBooksViewModel()
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                YearPublished = book.YearPublished,
                NumPages = book.NumPages,
                Publisher = book.Publisher,
                FrontPageUrl = book.FrontPage,
                DownloadUrl = book.DownloadUrl,
                Authors = authors,
                Genres = genres,
                AuthorId = book.AuthorId,
                GenreIds = genreIds,
            };
            return View(bookVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditBooksViewModel bookVM)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<Author> authors = await _service.GetAllAuthors();
                bookVM.Authors = authors;
                IEnumerable<Genre> genres = await _service.GetAllGenres();
                bookVM.Genres = genres;
                ModelState.AddModelError("", "Failed to edit book");
                return View(bookVM);
            }
            var result = await _photoService.AddPhotoAsync(bookVM.FrontPage);
            if (bookVM.DownloadPdf != null)
            {
                string folder = "BooksPdf/";
                bookVM.DownloadUrl = await UploadFile(folder, bookVM.DownloadPdf);
            }
            if (bookVM != null)
            {
                Book newBook = new Book()
                {
                    Id = bookVM.Id,
                    Title = bookVM.Title,
                    Description = bookVM.Description,
                    YearPublished = bookVM.YearPublished,
                    NumPages = bookVM.NumPages,
                    Publisher = bookVM.Publisher,
                    FrontPage = result.Url.ToString(),
                    DownloadUrl = bookVM.DownloadUrl,
                    AuthorId = bookVM.AuthorId,
                };
                _service.Update(id,newBook);
                IEnumerable<BookGenre> bookGenres = await _bookGenresService.GetAll();
                foreach (var bg in bookGenres)
                {
                    if (bg.BookId == id)
                    {
                        _bookGenresService.Delete(bg);
                    }
                }
                foreach (var genreId in bookVM.GenreIds)
                {
                    BookGenre bookGenre = new BookGenre()
                    {
                        BookId = bookVM.Id,
                        GenreId = genreId,
                    };
                    _bookGenresService.Add(bookGenre);
                }

                return Redirect("/Books/Details/" + id);
            }
            else
            {
                IEnumerable<Author> authors = await _service.GetAllAuthors();
                bookVM.Authors = authors;
                IEnumerable<Genre> genres = await _service.GetAllGenres();
                bookVM.Genres = genres;
                return View(bookVM);
            }
        }
        private async Task<string> UploadFile(string folderPath, IFormFile file)
        {
            if (folderPath == null)
            {
                throw new ArgumentNullException(nameof(folderPath), "Folder path cannot be null.");
            }

            // Combine folder path and file name

WebApplication1/Controllers/ReviewsController.cs
using e_shop.Data;
using e_shop.Data.Services;
using e_shop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using WebApplication1.viewModel;

namespace e_shop.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewsService _service;
        private readonly IBooksService bookService;
        private readonly HttpContextAccessor _httpContextAccessor;

        public ReviewsController(IReviewsService service, IBooksService bookService)
        {
            _service = service;
            this.bookService = bookService;
        }
        public async Task<IActionResult> Index(int id)
        {
            var allReviews = await _service.GetAllById(id);
            ReviewsViewModel newRVM = new ReviewsViewModel()
            {
                BookId = id,
                Reviews = allReviews
            };
            return View(newRVM);
        }
        public IActionResult Create()
        {
            var currentUser = _service.GetCurrentUserId();
            var newReview = new Review() { AppUser = currentUser };
            var newVM = new CreateReviewViewModel()
            {
                review = newReview,
                UserName=_service.GetCurrentUserUsername(currentUser)
            };
            return View(newVM); 
        }
        [HttpPost]
        public IActionResult Create(int id,CreateReviewViewModel reviewVM)
        {
            
            if (!ModelState.IsValid)
            {
                return View(reviewVM);
            }
            var newReview = new Review
            {
                BookId = id,
                AppUser = reviewVM.review.AppUser,
                Comment = reviewVM.review.Comment,
                Rating = reviewVM.review.Rating,
            };
            _service.Add(newReview);
            return Redirect("/Reviews/Index/"+id);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var reviewDetails = await _service.GetByIdAsync(id);
            if (reviewDetails == null)
            {
                return View("NotFound");
            }
            return View(reviewDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Review review)
        {
            if (!ModelState.IsValid)
            {
                return View(review);
            }
            await _service.UpdateAsync(review);
            return Redirect("/Reviews/Index/" +review.BookId);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var reviewDetails = await _service.GetByIdAsync(id);
            if (reviewDetails == null) return View("NotFound");
            return View(reviewDetails);
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reviewDetails = await _service.GetByIdAsync(id);
            if (reviewDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return Redirect("/Reviews/Index/" + reviewDetails.BookId);
        }
    }
}

WebApplication1/Views/Reviews/Create.cshtml
@using WebApplication1.viewModel
@model CreateReviewViewModel
@{
    ViewData["Title"] = "Add a new Review";
}
<div class="row text">
    <div class="col-md-8 offset-2" style="margin-top: 30px; color: darkcyan;">
        <p>
            <h4>Add a New Review</h4>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-action="Create">
                <div asp-asp-validation-summary="ModeOnly" class="text-danger"></div>
                <div>
                    <input asp-for="review.AppUser" class="form-control" hidden/>
                </div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="review.Comment" class="control-label"></label>
                    <input asp-for="review.Comment" class="form-control" />
                    <span asp-validation-for="review.Comment" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="review.Rating" class="control-label"></label>
                    <input asp-for="review.Rating" class="form-control" />
                    <span asp-validation-for="review.Rating" class="text-danger"></span>
                </div>
                <div class="form-gorup">
                    <button type="submit" class="btn btn-success float-right" style="margin-left: 88%; margin-top: 2%; font-size: 13px;" ><i class="bi bi-plus-square"></i>  Create</i></button>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication1/Views/Reviews/Delete.cshtml
@model Review
@{
    ViewData["Title"] = "Delete Review";
}
<div class="row text">
    <div class="col-md-8 offset-2" style="margin-top: 30px; color: darkcyan;">
        <p>
            <h4>Delete this Review</h4>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-action="Delete" method="post">
                <div asp-asp-validation-summary="ModeOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="AppUser" class="control-label"></label>
                    <input asp-for="AppUser" class="form-control" />
                    <span asp-validation-for="AppUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Comment" class="control-label"></label>
                    <input asp-for="Comment" class="form-control" />
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rating" class="control-label"></label>
                    <input asp-for="Rating" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-gorup">
                    <input type="hidden" asp-for="@Model.Id"/>
                    <input style="margin-left: 90%; margin-top: 2%; font-size: 13px;" type="submit" value="Confirm" class="btn btn-danger float-right" />
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication1/Views/Reviews/Edit.cshtml
@model Review
@{
    ViewData["Title"] = "Edit Review";
}
<div class="row text">
    <div class="col-md-8 offset-2" style="margin-top: 30px; color: darkcyan;">
        <p>
            <h4>Edit this Review</h4>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-action="Edit">
                <div>
                    <input type="hidden" asp-for="BookId" value="@Model.BookId"/>
                </div>
                <div asp-asp-validation-summary="ModeOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="AppUser" class="control-label"></label>
                    <input asp-for="AppUser" class="form-control" />
                    <span asp-validation-for="AppUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Comment" class="control-label"></label>
                    <input asp-for="Comment" class="form-control" />
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rating" class="control-label"></label>
                    <input asp-for="Rating" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-gorup">
                    <input style="margin-left: 92%; margin-top: 2%; font-size: 13px;" type="submit" value="Edit" class="btn btn-outline-success float-right" />
                </div>
            </form>

        </div>
    </div>
</div>

WebApplication1/Views/Reviews/Index.cshtml
@using WebApplication1
@using WebApplication1.viewModel
@model ReviewsViewModel
@{
    ViewData["Title"] = "List of Reviews";
}
@if(Model.Reviews.Count()==0)
{
    <div style="margin: 10%;">
        <h4 style="color: darkcyan">This book doesn't have reviews yet!</h4>
        <div>
            @if(User.Identity.IsAuthenticated)
            {
                <a style="font-size: 13px;" asp-controller="Reviews" asp-action="Create" asp-route-id="@Model.BookId" class="btn btn-success">
                    <i class="bi bi-plus-circle">Add New</i>
                </a>
            }
            <a asp-controller="Books" asp-action="Index" class="btn btn-info" style="font-size: 13px; margin-left: 24%;"><i class="bi bi-book">Go Back</i></a>
        </div>
    </div>
}
else{
    <div class="row" style="margin-top: 30px;">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                    <th>App User</th>
                    <th>Comment</th>
                    <th>Rating</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Reviews)
                {
                    <tr>
                        <td class="align-middle" style="font-size: 15px;">
                            @item.AppUserInfo.UserName
                        </td>
                            <td class="align-middle" style="font-size: 15px;">
                            @Html.DisplayFor(modelItem => item.Comment)
                        </td>
                        <td class="align-middle" style="font-size: 15px;">
                            @Html.DisplayFor(modelItem => item.Rating)
                        </td>
                        <td class="align-middle" style="font-size: 15px;">
                            @if(User.Identity.IsAuthenticated && User.GetUserId() == item.AppUser)
                            {
                                <a class="btn btn-danger" style="padding-left: 4px; padding-right: 4px; padding-top: 2px; padding-bottom: 2px; font-size: 14px;" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i></a>
                                    <a class="btn btn-outline-primary" style="padding-left: 4px; padding-right: 4px; padding-top: 2px; padding-bottom: 2px; font-size: 14px;" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                            }
                            @if(User.Identity.IsAuthenticated && User.IsInRole("admin"))
                            {
                                    <a class="btn btn-danger" style="padding-left: 4px; padding-right: 4px; padding-top: 2px; padding-bottom: 2px; font-size: 14px;" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i></a>
                            }
                         </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
    @if(User.Identity.IsAuthenticated)
    {
        <div class="text-white" style="position: fixed; right: 30px; bottom: 30px;">
            <a style="font-size: 13px;" asp-controller="Reviews" asp-action="Create" asp-route-id="@Model.BookId" class="btn btn-success">
                <i class="bi bi-plus-circle">Add New</i>
            </a>
        </div>
    }
}